site_name: docs.repo.trade
site_url: https://docs.repo.trade
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: false
    code: false
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

markdown_extensions:
  - toc:
      permalink: false
      toc_depth: 0
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Launch: launch.md
  - FAQs: faqs.md
  - Community: community.md
  - Whitepaper: whitepaper.md
  - Glossary: glossary.md
  - Short Story: short-story.md